version: "3.8"

services:

  app:
    container_name: parkd_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/Parkd
    restart: unless-stopped
    stdin_open: true  # docker run -i
    tty: true  # docker run -t

  db:
    image: postgres:14-alpine
    container_name: parkd_db
    env_file: .env
    volumes:
      - parkd_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  parkd_db_data:
